/**
 * Smart selector generation for DOM elements
 *
 * Three-phase pipeline architecture:
 * 1. Retarget — walk up to the intent element (interactive ancestor or keep clicked element)
 * 2. Generate candidates — produce all possible selectors with stability scores
 * 3. Rank and select — disambiguate non-unique candidates and pick the best one
 *
 * @module selector-generator
 */

import { findButtonByText } from './dom-utils';
import { querySelectorAllEnhanced, querySelectorAllEnhancedVisible } from './enhanced-selector';

// ============================================================================
// Types
// ============================================================================

export type StabilityFlag =
  | 'i18n-sensitive'
  | 'session-unstable'
  | 'environment-unstable'
  | 'structural'
  | 'portal-scoped';

export type SelectorQuality = 'good' | 'medium' | 'poor';

export interface SelectorInfo {
  selector: string;
  method: string;
  isUnique: boolean;
  matchCount: number;
  contextStrategy?: string;
  stabilityScore: number;
  warnings: string[];
  quality: SelectorQuality;
  flags: StabilityFlag[];
  isPortalScoped: boolean;
  overlayRole?: string;
  visibleMatchCount?: number;
}

interface Candidate {
  selector: string;
  score: number;
  method: string;
}

// ============================================================================
// Configuration
// ============================================================================

const SELECTOR_CONFIG = {
  testIdAttrs: ['data-testid', 'data-cy', 'data-test-id', 'data-qa', 'data-test-subj'] as const,
  interactiveTags: ['button', 'a'] as const,
  interactiveRoles: ['button', 'link', 'checkbox', 'radio', 'tab', 'menuitem', 'option', 'switch', 'combobox'] as const,
  formControlTags: ['input', 'select', 'textarea'] as const,
  semanticRoles: ['button', 'link', 'menuitem', 'option', 'tab', 'checkbox', 'radio', 'switch', 'combobox'] as const,
  maxTextLength: 50,
  maxRetargetDepth: 10,
  maxDisambiguationDepth: 15,
  maxScopingDepth: 8,
  genericButtonWords: [
    'new',
    'add',
    'save',
    'cancel',
    'close',
    'ok',
    'yes',
    'no',
    'edit',
    'delete',
    'remove',
    'update',
    'submit',
    'back',
    'next',
    'confirm',
    'apply',
    'reset',
    'clear',
    'search',
    'filter',
  ] as const,
} as const;

const CANDIDATE_SCORES = {
  testId: 10,
  scopedTestId: 15,
  cssId: 50,
  roleText: 100,
  roleContains: 110,
  ariaLabel: 120,
  buttonText: 130,
  placeholder: 140,
  title: 150,
  labelText: 160,
  name: 170,
  href: 180,
  compound: 500,
  nthOfType: 10000,
  nthMatch: 50000,
} as const;

const DISAMBIGUATION_PENALTIES = {
  parentTestId: 50,
  parentStableAttr: 70,
  overlayScope: 75,
  nthMatch: 1000,
} as const;

const OVERLAY_ROLES = ['dialog', 'alertdialog', 'menu', 'listbox', 'tooltip', 'combobox'] as const;

// ============================================================================
// Helpers
// ============================================================================

function isAutoGeneratedId(id: string): boolean {
  if (id.length > 20) {
    return true;
  }
  if (/^[a-f0-9]{8,}/.test(id)) {
    return true;
  }
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)) {
    return true;
  }
  if (/^id-\d+/.test(id)) {
    return true;
  }
  if (/^react-/.test(id)) {
    return true;
  }
  return false;
}

function isValidTestId(value: string | null): boolean {
  if (!value) {
    return false;
  }
  if (value.includes('[object Object]')) {
    return false;
  }
  if (value.trim() === '') {
    return false;
  }
  return true;
}

function normalizeText(text: string): string {
  return text
    .replace(/[\u200e\u200f]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function normalizeHref(href: string): string {
  try {
    const hashIndex = href.indexOf('#');
    const queryIndex = href.indexOf('?');
    let endIndex = href.length;
    if (hashIndex > 0) {
      endIndex = hashIndex;
    }
    if (queryIndex > 0 && queryIndex < endIndex) {
      endIndex = queryIndex;
    }
    return href.substring(0, endIndex);
  } catch {
    return href;
  }
}

function getAnyTestId(element: HTMLElement): string | null {
  for (const attr of SELECTOR_CONFIG.testIdAttrs) {
    if (element.hasAttribute(attr)) {
      const value = element.getAttribute(attr);
      if (isValidTestId(value)) {
        return value;
      }
    }
  }
  return null;
}

function getTestIdAttr(element: HTMLElement): string {
  return SELECTOR_CONFIG.testIdAttrs.find((attr) => element.hasAttribute(attr)) || 'data-testid';
}

const STABLE_CLASS_PATTERNS = [/^[a-z][a-z0-9-]*(__[a-z0-9-]+)?(--[a-z0-9-]+)?$/, /^[a-z][a-z0-9-]+$/];

function isStableClass(className: string): boolean {
  return STABLE_CLASS_PATTERNS.some((pattern) => pattern.test(className));
}

function isAutoGeneratedClass(className: string): boolean {
  if (isStableClass(className)) {
    return false;
  }
  if (className.startsWith('css-')) {
    return true;
  }
  if (/^[a-z]+-[a-z0-9]{6,}/.test(className)) {
    return true;
  }
  if (className.match(/^_[a-zA-Z0-9]{5,}$/)) {
    return true;
  }
  if (/[a-zA-Z0-9]{6,}/.test(className) && className.includes('-')) {
    return true;
  }
  if (className.startsWith('theme-')) {
    return true;
  }
  const utilityClasses = [
    'flex',
    'flex-row',
    'flex-col',
    'block',
    'inline',
    'hidden',
    'absolute',
    'relative',
    'fixed',
    'static',
    'w-full',
    'h-full',
    'p-0',
    'p-1',
    'p-2',
    'p-3',
    'p-4',
    'm-0',
    'm-1',
    'm-2',
    'm-3',
    'm-4',
    'text-left',
    'text-center',
    'text-right',
    'font-bold',
    'font-normal',
    'font-light',
  ];
  if (utilityClasses.includes(className)) {
    return true;
  }
  if (className.match(/^(theme|color|bg|border|rounded|shadow)-/)) {
    return true;
  }
  return false;
}

function getMeaningfulClasses(element: HTMLElement): string[] {
  if (!element.className || typeof element.className !== 'string') {
    return [];
  }
  return element.className
    .split(/\s+/)
    .filter(Boolean)
    .filter((cls) => !isAutoGeneratedClass(cls));
}

const DYNAMIC_ATTRIBUTE_PATTERNS = [
  /\[data-new-gr-c-s-check-loaded="[^"]*"\]/,
  /\[data-gr-ext-installed="[^"]*"\]/,
  /\[data-gr-ext-disabled="[^"]*"\]/,
  /\[data-testid="data-testid [^"]*"\]\[data-testid="data-testid [^"]*"\]/,
];

function cleanDynamicAttributes(selector: string): string {
  let cleaned = selector;
  for (const pattern of DYNAMIC_ATTRIBUTE_PATTERNS) {
    cleaned = cleaned.replace(pattern, '');
  }
  cleaned = cleaned.replace(/\.theme-(?:dark|light)/g, '');
  cleaned = cleaned.replace(/\s+/g, ' ').trim();
  return cleaned;
}

const UNSTABLE_DATA_ATTR_PATTERNS: RegExp[] = [
  /^data-emotion/,
  /^data-react/,
  /^data-state$/,
  /^data-focus/,
  /^data-hover/,
  /^data-active/,
  /^data-selected$/,
  /^data-disabled$/,
  /^data-checked$/,
  /^data-popper-/,
  /^data-radix-/,
  /^data-headlessui-/,
  /^data-new-gr-/,
  /^data-gr-/,
  /^data-testid$/,
  /^data-cy$/,
  /^data-test-id$/,
  /^data-qa$/,
  /^data-test-subj$/,
  /^data-mprt$/,
  /^data-uri$/,
  /^data-keybinding-context$/,
  /^data-mode-id$/,
  /^data-rfd-/,
];

function getStableDataAttr(element: HTMLElement): { name: string; value: string } | null {
  for (const attr of Array.from(element.attributes)) {
    if (!attr.name.startsWith('data-')) {
      continue;
    }
    if (UNSTABLE_DATA_ATTR_PATTERNS.some((p) => p.test(attr.name))) {
      continue;
    }
    if (!attr.value || attr.value.length > SELECTOR_CONFIG.maxTextLength) {
      continue;
    }
    if (attr.value === 'true' || attr.value === 'false') {
      continue;
    }
    if (/^\d+$/.test(attr.value)) {
      continue;
    }
    return { name: attr.name, value: attr.value };
  }
  return null;
}

// ============================================================================
// Overlay / Portal Detection
// ============================================================================

function findOverlayContext(element: HTMLElement): HTMLElement | null {
  let current: HTMLElement | null = element.parentElement;
  while (current) {
    const role = current.getAttribute('role');
    if (role && (OVERLAY_ROLES as readonly string[]).includes(role)) {
      return current;
    }
    if (current.classList.contains('modal') || current.hasAttribute('aria-modal') || current.tagName === 'DIALOG') {
      return current;
    }
    if (
      current.classList.contains('dropdown-menu') ||
      current.classList.contains('portal') ||
      current.getAttribute('data-popper-placement')
    ) {
      return current;
    }
    current = current.parentElement;
  }
  return null;
}

function buildOverlayScopedSelector(overlay: HTMLElement, baseSelector: string): string {
  const role = overlay.getAttribute('role');
  if (role) {
    return `[role="${role}"] ${baseSelector}`;
  }
  if (overlay.tagName === 'DIALOG') {
    return `dialog ${baseSelector}`;
  }
  if (overlay.hasAttribute('aria-modal')) {
    return `[aria-modal="true"] ${baseSelector}`;
  }
  if (overlay.classList.contains('modal')) {
    return `.modal ${baseSelector}`;
  }
  return baseSelector;
}

function getOverlayRole(overlay: HTMLElement | null): string | undefined {
  if (!overlay) {
    return undefined;
  }
  const role = overlay.getAttribute('role');
  if (role) {
    return role;
  }
  if (overlay.tagName === 'DIALOG') {
    return 'dialog';
  }
  if (overlay.hasAttribute('aria-modal')) {
    return 'modal';
  }
  return 'overlay';
}

// ============================================================================
// Phase 1: Retarget
// ============================================================================

/**
 * Walk up the DOM to find the user's "intent element."
 *
 * Rules (confirmed by design):
 * - Form controls (input/select/textarea/contentEditable) → keep as-is
 * - Non-interactive child of an interactive ancestor → retarget to the ancestor
 * - Non-interactive element with no interactive ancestor → keep as-is
 */
export function retargetElement(element: HTMLElement): HTMLElement {
  const tag = element.tagName.toLowerCase();
  const role = element.getAttribute('role');

  if ((SELECTOR_CONFIG.formControlTags as readonly string[]).includes(tag)) {
    return element;
  }
  if ((element as HTMLElement & { isContentEditable: boolean }).isContentEditable) {
    return element;
  }
  if ((SELECTOR_CONFIG.interactiveTags as readonly string[]).includes(tag)) {
    return element;
  }
  if (role && (SELECTOR_CONFIG.interactiveRoles as readonly string[]).includes(role)) {
    return element;
  }

  let current: HTMLElement | null = element.parentElement;
  let depth = 0;

  while (current && depth < SELECTOR_CONFIG.maxRetargetDepth) {
    const currentTag = current.tagName.toLowerCase();
    const currentRole = current.getAttribute('role');

    if ((SELECTOR_CONFIG.interactiveTags as readonly string[]).includes(currentTag)) {
      return current;
    }
    if (currentRole && (SELECTOR_CONFIG.interactiveRoles as readonly string[]).includes(currentRole)) {
      return current;
    }

    current = current.parentElement;
    depth++;
  }

  return element;
}

// ============================================================================
// Phase 2: Candidate Generators
// ============================================================================

function candidateTestId(element: HTMLElement): Candidate | null {
  const testId = getAnyTestId(element);
  if (!testId) {
    return null;
  }
  const tag = element.tagName.toLowerCase();
  const attr = getTestIdAttr(element);
  return { selector: `${tag}[${attr}='${testId}']`, score: CANDIDATE_SCORES.testId, method: 'data-testid' };
}

function candidateScopedTestId(element: HTMLElement): Candidate | null {
  const testId = getAnyTestId(element);
  if (!testId) {
    return null;
  }
  const tag = element.tagName.toLowerCase();
  const attr = getTestIdAttr(element);
  const base = `${tag}[${attr}='${testId}']`;

  let current = element.parentElement;
  let depth = 0;
  while (current && depth < SELECTOR_CONFIG.maxScopingDepth) {
    const parentTestId = getAnyTestId(current);
    if (parentTestId) {
      const pTag = current.tagName.toLowerCase();
      const pAttr = getTestIdAttr(current);
      return {
        selector: `${pTag}[${pAttr}='${parentTestId}'] ${base}`,
        score: CANDIDATE_SCORES.scopedTestId,
        method: 'scoped-testid',
      };
    }
    current = current.parentElement;
    depth++;
  }
  return null;
}

function candidateTestIdPlusHref(element: HTMLElement): Candidate | null {
  if (element.tagName !== 'A') {
    return null;
  }
  const testId = getAnyTestId(element);
  const rawHref = element.getAttribute('href');
  if (!testId || !rawHref) {
    return null;
  }
  const attr = getTestIdAttr(element);
  const href = normalizeHref(rawHref);
  return {
    selector: `a[${attr}='${testId}'][href='${href}']`,
    score: CANDIDATE_SCORES.testId + 2,
    method: 'testid-href',
  };
}

function candidateId(element: HTMLElement): Candidate | null {
  if (!element.id || isAutoGeneratedId(element.id)) {
    return null;
  }
  return { selector: `#${element.id}`, score: CANDIDATE_SCORES.cssId, method: 'id' };
}

function candidateRoleName(element: HTMLElement): Candidate | null {
  const role = element.getAttribute('role');
  if (!role || !(SELECTOR_CONFIG.semanticRoles as readonly string[]).includes(role)) {
    return null;
  }
  const text = normalizeText(element.textContent || '');
  if (text.length === 0 || text.length > SELECTOR_CONFIG.maxTextLength) {
    const tag = element.tagName.toLowerCase();
    return { selector: `${tag}[role='${role}']`, score: CANDIDATE_SCORES.roleContains + 50, method: 'role' };
  }
  if (text.length < 20) {
    return { selector: `[role='${role}']:text('${text}')`, score: CANDIDATE_SCORES.roleText, method: 'role-text' };
  }
  return {
    selector: `[role='${role}']:contains('${text}')`,
    score: CANDIDATE_SCORES.roleContains,
    method: 'role-contains',
  };
}

function candidateAriaLabel(element: HTMLElement): Candidate | null {
  const ariaLabel = element.getAttribute('aria-label');
  if (!ariaLabel || ariaLabel.length > SELECTOR_CONFIG.maxTextLength) {
    return null;
  }
  const tag = element.tagName.toLowerCase();
  return { selector: `${tag}[aria-label='${ariaLabel}']`, score: CANDIDATE_SCORES.ariaLabel, method: 'aria-label' };
}

function candidateButtonText(element: HTMLElement): Candidate[] {
  const candidates: Candidate[] = [];
  if (element.tagName !== 'BUTTON' && element.getAttribute('role') !== 'button') {
    return candidates;
  }
  const text = normalizeText(element.textContent || '');
  if (text.length === 0 || text.length > SELECTOR_CONFIG.maxTextLength) {
    return candidates;
  }

  const lowerText = text.toLowerCase();
  const isGeneric =
    text.length < 4 ||
    SELECTOR_CONFIG.genericButtonWords.includes(lowerText as (typeof SELECTOR_CONFIG.genericButtonWords)[number]);

  if (!isGeneric) {
    const buttons = findButtonByText(text);
    if (buttons.length === 1) {
      candidates.push({ selector: text, score: CANDIDATE_SCORES.buttonText, method: 'button-text' });
    }
  }

  const tag = element.tagName.toLowerCase();
  if (text.length < 20) {
    candidates.push({
      selector: `${tag}:text('${text}')`,
      score: CANDIDATE_SCORES.buttonText + 5,
      method: 'button-css-text',
    });
  } else {
    candidates.push({
      selector: `${tag}:contains('${text}')`,
      score: CANDIDATE_SCORES.buttonText + 10,
      method: 'button-css-contains',
    });
  }
  return candidates;
}

function candidatePlaceholder(element: HTMLElement): Candidate | null {
  if (element.tagName !== 'INPUT' && element.tagName !== 'TEXTAREA') {
    return null;
  }
  const placeholder = element.getAttribute('placeholder');
  if (!placeholder || placeholder.length === 0 || placeholder.length > SELECTOR_CONFIG.maxTextLength) {
    return null;
  }
  const tag = element.tagName.toLowerCase();
  return {
    selector: `${tag}[placeholder='${placeholder}']`,
    score: CANDIDATE_SCORES.placeholder,
    method: 'placeholder',
  };
}

function candidateTitle(element: HTMLElement): Candidate | null {
  const title = element.getAttribute('title');
  if (!title || title.length === 0 || title.length > SELECTOR_CONFIG.maxTextLength) {
    return null;
  }
  const tag = element.tagName.toLowerCase();
  return { selector: `${tag}[title='${title}']`, score: CANDIDATE_SCORES.title, method: 'title' };
}

function candidateLabelText(element: HTMLElement): Candidate | null {
  if (element.tagName !== 'LABEL') {
    return null;
  }
  const text = normalizeText(element.textContent || '');
  if (text.length === 0 || text.length > SELECTOR_CONFIG.maxTextLength) {
    return null;
  }
  return { selector: `label:contains('${text}')`, score: CANDIDATE_SCORES.labelText, method: 'label-text' };
}

function candidateName(element: HTMLElement): Candidate | null {
  const tag = element.tagName.toLowerCase();
  if (!['input', 'textarea', 'select'].includes(tag)) {
    return null;
  }
  const name = element.getAttribute('name');
  if (!name) {
    return null;
  }
  if (tag === 'input') {
    const inputType = (element as HTMLInputElement).type?.toLowerCase();
    if (inputType === 'radio' || inputType === 'checkbox') {
      return null;
    }
  }
  return { selector: `${tag}[name='${name}']`, score: CANDIDATE_SCORES.name, method: 'name' };
}

function candidateHref(element: HTMLElement): Candidate | null {
  if (element.tagName !== 'A') {
    return null;
  }
  const rawHref = element.getAttribute('href');
  if (!rawHref) {
    return null;
  }
  const href = normalizeHref(rawHref);
  return { selector: `a[href='${href}']`, score: CANDIDATE_SCORES.href, method: 'href' };
}

function candidateCompound(element: HTMLElement): Candidate | null {
  const tag = element.tagName.toLowerCase();
  const parts: string[] = [tag];

  const meaningfulClasses = getMeaningfulClasses(element);
  if (meaningfulClasses.length > 0) {
    parts.push(`.${meaningfulClasses[0]}`);
  }

  for (const attr of Array.from(element.attributes)) {
    if (
      attr.name.startsWith('data-') &&
      !UNSTABLE_DATA_ATTR_PATTERNS.some((p) => p.test(attr.name)) &&
      attr.value.length < SELECTOR_CONFIG.maxTextLength &&
      attr.value !== 'true' &&
      attr.value !== 'false' &&
      !/^\d+$/.test(attr.value)
    ) {
      parts.push(`[${attr.name}='${attr.value}']`);
      break;
    }
  }

  if (tag === 'a' && element.hasAttribute('href')) {
    const href = normalizeHref(element.getAttribute('href')!);
    parts.push(`[href='${href}']`);
  }

  if (parts.length <= 1) {
    return null;
  }
  return { selector: cleanDynamicAttributes(parts.join('')), score: CANDIDATE_SCORES.compound, method: 'compound' };
}

function candidateNthOfType(element: HTMLElement): Candidate | null {
  if (!element.parentElement) {
    return null;
  }
  const tag = element.tagName.toLowerCase();
  const siblings = Array.from(element.parentElement.children).filter((el) => el.tagName === element.tagName);
  const index = siblings.indexOf(element) + 1;
  if (index <= 0) {
    return null;
  }
  const meaningfulClasses = getMeaningfulClasses(element);
  const classStr = meaningfulClasses.length > 0 ? `.${meaningfulClasses[0]}` : '';
  return {
    selector: `${tag}${classStr}:nth-of-type(${index})`,
    score: CANDIDATE_SCORES.nthOfType,
    method: 'nth-of-type',
  };
}

function generateCandidates(element: HTMLElement): Candidate[] {
  const candidates: Candidate[] = [];
  const push = (c: Candidate | null) => {
    if (c) {
      candidates.push(c);
    }
  };

  push(candidateTestId(element));
  push(candidateScopedTestId(element));
  push(candidateTestIdPlusHref(element));
  push(candidateId(element));
  push(candidateRoleName(element));
  push(candidateAriaLabel(element));
  candidates.push(...candidateButtonText(element));
  push(candidatePlaceholder(element));
  push(candidateTitle(element));
  push(candidateLabelText(element));
  push(candidateName(element));
  push(candidateHref(element));
  push(candidateCompound(element));
  push(candidateNthOfType(element));

  return candidates;
}

// ============================================================================
// Phase 3: Disambiguate and Rank
// ============================================================================

function testUniqueness(
  selector: string,
  element: HTMLElement,
  method: string,
  inOverlay = false
): { matchCount: number; containsTarget: boolean } {
  try {
    if (method === 'button-text') {
      const buttons = findButtonByText(selector);
      return { matchCount: buttons.length, containsTarget: buttons.includes(element as HTMLButtonElement) };
    }
    const matchFn = inOverlay ? querySelectorAllEnhancedVisible : querySelectorAllEnhanced;
    const matches = matchFn(selector);
    return { matchCount: matches.elements.length, containsTarget: matches.elements.includes(element) };
  } catch {
    return { matchCount: 0, containsTarget: false };
  }
}

type AncestorScopeType = 'testid' | 'id' | 'data-attr';

interface AncestorScope {
  selector: string;
  element: HTMLElement;
  depth: number;
  type: AncestorScopeType;
}

/**
 * Collect ALL ancestor scopes (testid, id, stable data-attr) from closest to farthest.
 * Returns them ordered nearest-first so disambiguation can try the tightest scope first.
 */
function findAllAncestorScopes(element: HTMLElement): AncestorScope[] {
  const scopes: AncestorScope[] = [];
  let current = element.parentElement;
  let depth = 0;

  while (current && depth < SELECTOR_CONFIG.maxDisambiguationDepth) {
    const testId = getAnyTestId(current);
    if (testId) {
      const tag = current.tagName.toLowerCase();
      const attr = getTestIdAttr(current);
      scopes.push({ selector: `${tag}[${attr}='${testId}']`, element: current, depth, type: 'testid' });
    } else if (current.id && !isAutoGeneratedId(current.id)) {
      scopes.push({ selector: `#${current.id}`, element: current, depth, type: 'id' });
    } else {
      const stableAttr = getStableDataAttr(current);
      if (stableAttr) {
        const tag = current.tagName.toLowerCase();
        scopes.push({
          selector: `${tag}[${stableAttr.name}='${stableAttr.value}']`,
          element: current,
          depth,
          type: 'data-attr',
        });
      }
    }

    current = current.parentElement;
    depth++;
  }
  return scopes;
}

/**
 * Find the direct child of `ancestor` that is an ancestor-or-self of `descendant`.
 */
function findDirectChildBranch(ancestor: HTMLElement, descendant: HTMLElement): HTMLElement | null {
  let current: HTMLElement | null = descendant;
  while (current && current.parentElement !== ancestor) {
    current = current.parentElement;
  }
  return current;
}

function disambiguate(
  candidate: Candidate,
  element: HTMLElement,
  ancestorScopes: AncestorScope[] = findAllAncestorScopes(element),
  inOverlay = false
): Candidate[] {
  const results: Candidate[] = [];

  // Strategy 1: Try each ancestor scope from closest to farthest
  for (const scope of ancestorScopes) {
    // 1a: Simple descendant scoping
    const scoped = `${scope.selector} ${candidate.selector}`;
    const { matchCount, containsTarget } = testUniqueness(scoped, element, candidate.method, inOverlay);
    if (matchCount === 1 && containsTarget) {
      const penalty =
        scope.type === 'testid' ? DISAMBIGUATION_PENALTIES.parentTestId : DISAMBIGUATION_PENALTIES.parentStableAttr;
      results.push({
        selector: cleanDynamicAttributes(scoped),
        score: candidate.score + penalty,
        method: candidate.method,
      });
      break;
    }

    // 1b: Scoped nth-child within this ancestor
    const branch = findDirectChildBranch(scope.element, element);
    if (branch) {
      const childIndex = Array.from(scope.element.children).indexOf(branch) + 1;
      if (childIndex > 0) {
        const childTag = branch.tagName.toLowerCase();
        const suffix = branch === element ? '' : ` ${candidate.selector}`;
        const nthChildScoped = `${scope.selector} > ${childTag}:nth-child(${childIndex})${suffix}`;
        const nthResult = testUniqueness(nthChildScoped, element, candidate.method, inOverlay);
        if (nthResult.matchCount === 1 && nthResult.containsTarget) {
          const penalty =
            scope.type === 'testid' ? DISAMBIGUATION_PENALTIES.parentTestId : DISAMBIGUATION_PENALTIES.parentStableAttr;
          results.push({
            selector: cleanDynamicAttributes(nthChildScoped),
            score: candidate.score + penalty,
            method: candidate.method,
          });
          break;
        }
      }
    }
  }

  // Strategy 2: Overlay scoping (always use visibility matching here)
  if (results.length === 0) {
    const overlay = findOverlayContext(element);
    if (overlay) {
      const overlayScoped = buildOverlayScopedSelector(overlay, candidate.selector);
      if (overlayScoped !== candidate.selector) {
        const { matchCount, containsTarget } = testUniqueness(overlayScoped, element, candidate.method, true);
        if (matchCount === 1 && containsTarget) {
          results.push({
            selector: cleanDynamicAttributes(overlayScoped),
            score: candidate.score + DISAMBIGUATION_PENALTIES.overlayScope,
            method: candidate.method,
          });
        }
      }
    }
  }

  // Strategy 3: nth-match (last resort)
  if (results.length === 0) {
    try {
      const matchFn = inOverlay ? querySelectorAllEnhancedVisible : querySelectorAllEnhanced;
      const allMatches = matchFn(candidate.selector);
      const idx = allMatches.elements.indexOf(element);
      if (idx >= 0) {
        results.push({
          selector: cleanDynamicAttributes(`${candidate.selector}:nth-match(${idx + 1})`),
          score: candidate.score + DISAMBIGUATION_PENALTIES.nthMatch,
          method: candidate.method,
        });
      }
    } catch {
      /* custom pseudo may not support nested nth-match */
    }
  }

  return results;
}

interface ScoredCandidate extends Candidate {
  matchCount: number;
}

function rankAndSelect(candidates: Candidate[], element: HTMLElement): ScoredCandidate {
  const scored: ScoredCandidate[] = [];
  const ancestorScopes = findAllAncestorScopes(element);
  const inOverlay = findOverlayContext(element) !== null;

  for (const candidate of candidates) {
    const { matchCount, containsTarget } = testUniqueness(candidate.selector, element, candidate.method, inOverlay);

    if (matchCount === 0 || !containsTarget) {
      continue;
    }

    if (matchCount === 1) {
      if (candidate.method !== 'button-text' && candidate.method !== 'scoped-testid') {
        let foundScope = false;
        for (const scope of ancestorScopes) {
          const scoped = `${scope.selector} ${candidate.selector}`;
          const scopedResult = testUniqueness(scoped, element, candidate.method, inOverlay);
          if (scopedResult.matchCount === 1 && scopedResult.containsTarget) {
            scored.push({
              selector: cleanDynamicAttributes(scoped),
              score: candidate.score,
              method: candidate.method,
              matchCount: 1,
            });
            foundScope = true;
            break;
          }
        }
        if (!foundScope) {
          scored.push({ ...candidate, matchCount });
        }
      } else {
        scored.push({ ...candidate, matchCount });
      }
      continue;
    }

    if (candidate.method === 'button-text') {
      continue;
    }

    const disambiguated = disambiguate(candidate, element, ancestorScopes, inOverlay);
    for (const d of disambiguated) {
      scored.push({ ...d, matchCount: 1 });
    }
  }

  if (scored.length === 0) {
    // No attribute / text / structural candidate matched — fall back to a positional
    // `:nth-of-type` selector. This is brittle (any sibling reorder breaks it) but
    // strictly better than returning nothing: at least the recorded step targets
    // *something*, and the Selector Health badge will show red so the author notices.
    const tag = element.tagName.toLowerCase();
    let nthIndex = 1;
    if (element.parentElement) {
      const siblings = Array.from(element.parentElement.children).filter((el) => el.tagName === element.tagName);
      const idx = siblings.indexOf(element);
      if (idx >= 0) {
        nthIndex = idx + 1;
      }
    }
    const fallbackSelector = `${tag}:nth-of-type(${nthIndex})`;
    const { matchCount, containsTarget } = testUniqueness(fallbackSelector, element, 'fallback', inOverlay);
    return {
      selector: fallbackSelector,
      score: CANDIDATE_SCORES.nthMatch,
      method: 'fallback',
      matchCount: containsTarget ? matchCount : 0,
    };
  }

  scored.sort((a, b) => a.score - b.score);
  return scored[0]!;
}

// ============================================================================
// Public API
// ============================================================================

/**
 * Generate the best CSS selector for a DOM element.
 *
 * Three-phase pipeline:
 * 1. Retarget to the intent element (interactive ancestor or clicked element)
 * 2. Generate all candidate selectors with stability scores
 * 3. Disambiguate non-unique candidates and return the best one
 */
export function generateBestSelector(
  element: HTMLElement,
  _options?: { clickX?: number; clickY?: number; hoveredElement?: HTMLElement }
): string {
  const target = retargetElement(element);
  const candidates = generateCandidates(target);
  const winner = rankAndSelect(candidates, target);
  return winner.selector;
}

/**
 * Get detailed information about the selector generated for an element.
 */
export function getSelectorInfo(element: HTMLElement): SelectorInfo {
  const target = retargetElement(element);
  const candidates = generateCandidates(target);
  const winner = rankAndSelect(candidates, target);

  const { selector, method, matchCount } = winner;
  const isUnique = matchCount === 1;

  const overlayContext = findOverlayContext(target);
  const isPortalScoped =
    overlayContext !== null ||
    selector.includes('[role="dialog"]') ||
    selector.includes('[role="menu"]') ||
    selector.includes('[aria-modal="true"]');
  const overlayRole = getOverlayRole(overlayContext);

  let contextStrategy: string | undefined;
  if (selector.includes(':nth-match(')) {
    contextStrategy = 'nth-match';
  } else if (selector.includes(' + ')) {
    contextStrategy = 'sibling';
  } else if (isPortalScoped) {
    contextStrategy = 'portal-scoped';
  } else if (selector.includes(' ') && !selector.includes(':contains(') && !selector.includes(':text(')) {
    contextStrategy = 'parent-context';
  }

  const stabilityScore =
    winner.score <= 20 ? 100 : winner.score <= 60 ? 90 : winner.score <= 150 ? 70 : winner.score <= 500 ? 50 : 20;
  const flags = computeStabilityFlags(selector, method);
  const quality = computeQuality(stabilityScore, flags);

  const warnings: string[] = [];
  if (stabilityScore < 30) {
    warnings.push('Selector depends on element position and may break if page structure changes');
  }
  if (selector.includes(':nth-match(') || selector.includes(':nth-of-type(')) {
    warnings.push('Consider adding a data-testid to this element for more stable selection');
  }
  if (!isUnique) {
    warnings.push(`Selector matches ${matchCount} elements — may cause unexpected behavior`);
  }
  if (matchCount === 0) {
    warnings.push('Selector does not match any elements — element may have been removed');
  }
  if (flags.includes('i18n-sensitive')) {
    warnings.push('Selector uses translatable text — may break in different locales');
  }
  if (flags.includes('session-unstable')) {
    warnings.push('Selector uses framework-generated ID — may change between sessions');
  }
  if (flags.includes('environment-unstable')) {
    warnings.push('Selector contains instance-specific data — may not work in different environments');
  }

  return {
    selector,
    method,
    isUnique,
    matchCount,
    contextStrategy,
    stabilityScore,
    warnings,
    quality,
    flags,
    isPortalScoped,
    overlayRole,
  };
}

/**
 * Generate fallback/alternative selectors for an element, ordered by stability.
 */
export function generateFallbackSelectors(element: HTMLElement, primarySelector: string): string[] {
  const target = retargetElement(element);
  const candidates = generateCandidates(target);
  const scored: ScoredCandidate[] = [];

  for (const candidate of candidates) {
    if (candidate.selector === primarySelector) {
      continue;
    }
    const { matchCount, containsTarget } = testUniqueness(candidate.selector, target, candidate.method);
    if (matchCount === 0 || !containsTarget) {
      continue;
    }
    if (matchCount === 1) {
      scored.push({ ...candidate, matchCount });
      continue;
    }
    if (candidate.method !== 'button-text') {
      const disambiguated = disambiguate(candidate, target);
      for (const d of disambiguated) {
        scored.push({ ...d, matchCount: 1 });
      }
    }
  }

  scored.sort((a, b) => a.score - b.score);

  const seen = new Set<string>([primarySelector]);
  const result: string[] = [];
  for (const s of scored) {
    if (!seen.has(s.selector)) {
      seen.add(s.selector);
      result.push(s.selector);
      if (result.length >= 4) {
        break;
      }
    }
  }
  return result;
}

/**
 * @deprecated Caching has been removed — this is a no-op for backward compatibility.
 */
export function clearSelectorCache(): void {
  // No-op
}

// ============================================================================
// Stability Analysis (internal)
// ============================================================================

function computeStabilityFlags(selector: string, method: string): StabilityFlag[] {
  const flags: StabilityFlag[] = [];

  if (
    selector.includes('aria-label') ||
    selector.includes('placeholder') ||
    selector.includes("title='") ||
    selector.includes('title="') ||
    selector.includes(':contains(') ||
    selector.includes(':text(')
  ) {
    flags.push('i18n-sensitive');
  }

  if (
    /react-[a-z0-9]+/i.test(selector) ||
    /radix-[a-z0-9]+/i.test(selector) ||
    /headlessui-[a-z0-9]+/i.test(selector) ||
    /mui-[a-z0-9]+/i.test(selector) ||
    /:r[0-9a-z]+:/i.test(selector) ||
    /id-\d+/.test(selector)
  ) {
    flags.push('session-unstable');
  }

  if (
    selector.includes(':nth-of-type') ||
    selector.includes(':nth-match') ||
    selector.includes(':nth-child') ||
    method === 'nth-of-type' ||
    method === 'nth-match'
  ) {
    flags.push('structural');
  }

  if (
    selector.includes('[role="dialog"]') ||
    selector.includes('[role="alertdialog"]') ||
    selector.includes('[role="menu"]') ||
    selector.includes('[role="listbox"]') ||
    selector.includes('[role="tooltip"]') ||
    selector.includes('[role="combobox"]') ||
    selector.includes('[aria-modal="true"]') ||
    selector.includes('dialog ')
  ) {
    flags.push('portal-scoped');
  }

  if (
    /[a-f0-9]{8,}/i.test(selector) ||
    /[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/i.test(selector) ||
    selector.includes('/d/') ||
    selector.includes('orgId=') ||
    selector.includes('uid=')
  ) {
    flags.push('environment-unstable');
  }

  return flags;
}

function computeQuality(stabilityScore: number, flags: StabilityFlag[]): SelectorQuality {
  if (stabilityScore < 40 || (flags.includes('structural') && stabilityScore < 60)) {
    return 'poor';
  }
  if (stabilityScore >= 80 && !flags.includes('structural') && !flags.includes('session-unstable')) {
    return 'good';
  }
  return 'medium';
}
